# Generated by Django 5.1.6 on 2025-03-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0002_borrower_email_borrower_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('borrow_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('borrow_date', models.DateTimeField(blank=True, null=True)),
                ('artist', models.CharField(max_length=100)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('borrow_date', models.DateTimeField(blank=True, null=True)),
                ('director', models.CharField(max_length=100)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MediaItem',
        ),
    ]
