# Generated by Django 5.1.6 on 2025-03-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0003_boardgame_alter_borrower_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='empruntable',
            field=models.BooleanField(default=False),
        ),
    ]
