# Generated by Django 5.1.6 on 2025-03-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0004_boardgame_empruntable'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='empruntable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cd',
            name='empruntable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='empruntable',
            field=models.BooleanField(default=True),
        ),
    ]
